version: "3"
services:
    server1:
        build: server1
    server2:
        build: server2
    proxy:
        build: proxy
        # volumes: 
          # - ./proxy/html:/usr/share/nginx/html
          # - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
 

